name: AncSeq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - exonerate=2.4.0
  - emboss=6.6.0
  - mafft=7.526
  - iqtree=2.3.6
  - biopython=1.84
  - jupyter=1.1.1
  - jupyterlab=4.2.5
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - pip
  - pip:
    - notebook>=7.0.0
